src/making/urls.py
from django.urls import path
from making import views 

app_name = 'making'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('projects/<int:project_id>/', views.project, name='project'),
    path('projects/', views.projects, name='projects'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('create_profile/', views.create_profile, name='create_profile'),
    path('view_profile/', views.view_profile, name="view_profile",),
    path('update_profile/',views.update_profile, name="update_profile"),
    path('select_profile/', views.select_profile, name="select_profile"),
    path('add_tool/', views.add_tool, name="add_tool"),
    path('create_syllabus/', views.create_syllabus, name="create_syllabus"),
]

src/making_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('', include('making.urls')),
    path('admin/', admin.site.urls),
]

src/making/forms.py
from django.forms import ModelForm, Form, BaseFormSet
from making.models import Requirements, Tool, UserProfile, Project
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django import forms 

# for registering
class UserForm(ModelForm):  
    password = forms.CharField(widget=forms.PasswordInput())
    username = forms.EmailField(max_length=64, label="Email")
    class Meta:
        model = User
        fields = ('username', 'password',)

# cant use the model form for logging in because Django assumes you are registering a new user every time
class LoginForm(Form):
    username = forms.EmailField(max_length=64, label="Email")
    password = forms.CharField(widget=forms.PasswordInput())

class ProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_name',)

class RequirementsForm(ModelForm):
    class Meta:
        model = Requirements
        fields = '__all__'

# name choices are just every tool that's been used in a project
class ToolForm(ModelForm):
    CHOICES = Tool.choices_objects.get_choices
    name = forms.ChoiceField(choices=CHOICES)
    class Meta:
        model = Tool
        fields = ('name','skill_level')

class SyllabusForm(Form):
    # get all project ID's and titles
    CHOICES = Project.choices_objects.get_choices()
    end_project = forms.ChoiceField(choices=CHOICES)

class SwitchProfileForm(Form):
    #the choices are decided in the View because it depends on the user profile
    profile = forms.ChoiceField()

# tool formset validation 
class BaseToolFormSet(BaseFormSet):
    # checks no tools have the same name
    def clean(self):
        # dont bother unless each form is valid on its own
        if any(self.errors):
            return 
        names = []
        for form in self.forms:
            if self.can_delete and self._should_delete_form(form):
                continue
            name = form.cleaned_data.get('name')
            if name in names:
                raise ValidationError("Cannot add same tool twice.")
            names.append(name)

src/making/views.py
from django.shortcuts import render, redirect
from making.forms import RequirementsForm, ToolForm, UserForm, LoginForm, ProfileForm, SyllabusForm, SwitchProfileForm, BaseToolFormSet
from making.models import Tool, UserProfile, Project
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from copy import deepcopy
from django.forms import formset_factory
from django.core.exceptions import ValidationError

# helper function that gets current user profile object
def getProfile(request):
    try:
        user_profile = UserProfile.objects.get(id=request.session['user_profile'])
    except:
        user_profile = None
    return user_profile

def index(request):
    user_profile = getProfile(request)
    return render(request, 'making/index.html', context = {'user_profile': user_profile})

def about(request):
    return render(request, 'making/about.html')

# view of multiple projects, just grabs the first 10
def projects(request):
    user_profile = getProfile(request)
    project_objs = Project.objects.all()[:10]
    # get all the preview dicts of the objects
    projects = [Project.preview_dict(i) for i in project_objs]
    return render(request, 'making/projects.html', context={'user_profile':user_profile,'projects': projects})

# specific project
def project(request, project_id):
    user_profile = getProfile(request)
    # turn profile into a dict 
    if user_profile:
        user_profile = UserProfile.view_dict(user_profile)
    # need to order profile tools in the same order as project (zip them together)
    paths = None
    try:
        #is there a project with that id?
        project_obj = Project.objects.get(id=project_id)
        # turn into dictionary, get the related requirements and tool objects (if any tools)
        project = Project.view_dict(project_obj)
        paths = Project.get_img_path(project_obj)
    except Project.DoesNotExist:
        project = None 
    return render(request, 'making/project.html', context={'user_profile':user_profile,'project': project,'paths':paths})

def register(request):
    # tells the template if there was an issue in registration
    error = None 
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        if user_form.is_valid(): 
            # save users form data to the db 
            user = user_form.save() 
            # hash password, update user object
            user.set_password(user.password)
            user.save() 
            # logs the user in and takes them to create profile page
            login(request, user)  
            # they dont have any profiles yet          
            request.session['user_profile'] = None 
            return redirect(reverse('making:create_profile'))             
        else: 
            error = user_form.errors
    else: 
        user_form = UserForm()
    return render(request, 'making/register.html', context = {'user_form': user_form, 'error': error})

def user_login(request):
    error = False
    if request.method == 'POST':
        user_form = LoginForm(request.POST)
        username = user_form['username'].value()
        password = user_form['password'].value()
        # are details valid?
        user = authenticate(username=username, password=password)
        if user:
            login(request, user) 
            # initialise session variable  
            request.session['user_profile'] = None          
            profiles = UserProfile.objects.filter(user=user)
            # if the user just has 1 profile, set the session profile to that
            if len(profiles) == 1:
                request.session['user_profile'] = profiles[0].pk
                return redirect(reverse('making:index'))  
            # if the user doesn't have any profiles, redirect them to create profile
            elif len(profiles) == 0:
                return redirect(reverse('making:create_profile'))
            # otherwise redirect them to select profile
            else: 
                return redirect(reverse('making:select_profile'))   
        else:
            error = True         
    else:
        user_form = LoginForm()
    return render(request, 'making/login.html', context={'user_form': user_form, 'error': error})
 
@login_required
def user_logout(request):
    # also deletes session data 
    logout(request)
    return redirect(reverse('making:index'))

@login_required
def create_profile(request):
    # tells the template if creation was successful 
    registered = False 
    user_profile = getProfile(request)
    ToolFormSet = formset_factory(ToolForm, extra=0, max_num=6, formset=BaseToolFormSet)

    if request.method == 'POST':
        profile_form = ProfileForm(request.POST)
        requirements_form = RequirementsForm(request.POST)
        toolFormSet = ToolFormSet(request.POST) 
        # if the forms are valid
        if profile_form.is_valid() and requirements_form.is_valid() and toolFormSet.is_valid(): 
            profile = profile_form.save(commit=False)
            profile.user = request.user       
            requirements = requirements_form.save()
            profile.requirements = requirements
            profile.save()           
            registered = True
            # change the session profile to this new one
            request.session['user_profile'] = profile.pk 
            user_profile = getProfile(request)
            # then try to add the tools 
            for form in toolFormSet: 
                tool = form.save(commit=False)
                tool.requirements = user_profile.requirements
                try:
                    tool.full_clean()
                    tool.save()
                except ValidationError as e: 
                    print(e)
        else: 
            print(profile_form.errors)
    else: 
        profile_form = ProfileForm()
        requirements_form = RequirementsForm()
        toolFormSet = ToolFormSet()
    return render(request, 'making/create_profile.html', context = {'user_profile':user_profile,'profile_form': profile_form, 'requirements_form': requirements_form,'toolFormSet':toolFormSet,'registered': registered})

@login_required
def view_user(request):
    user_profile = getProfile(request)
    return render(request, 'making/view_user.html', context = {'user_profile': user_profile})

@login_required
def view_profile(request):
    # get current profile object
    user_profile = getProfile(request)
    #if user doesn't have a profile selected, redirect to homepage
    if not user_profile: 
        return redirect(reverse('making:index'))
    # turn profile obj into dictionary, get the related requirements and tools (if any)
    profile = UserProfile.view_dict(user_profile)
    return render(request, 'making/view_profile.html', context = {'user_profile': user_profile,'profile':profile})

@login_required 
def update_profile(request):
    user_profile = getProfile(request)
    # if they dont have a profile selected, redirect to select_profile
    if not user_profile:
        return redirect(reverse('making:select_profile'))

    ToolFormSet = formset_factory(ToolForm,extra=0)
    # get all the profiles related tool objects
    tool_qs = user_profile.requirements.tool_set.all()    
    # dictionary version of the tool objects
    tools = tool_qs.values() 

    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, instance=user_profile)
        requirements_form = RequirementsForm(request.POST, instance=user_profile.requirements)
        toolFormSet = ToolFormSet(request.POST,initial=tools)

        for form in toolFormSet.forms:
            form.fields['name'].choices = [(form.initial['name'],form.initial['name'])]

        if profile_form.is_valid() and requirements_form.is_valid() and toolFormSet.is_valid():
            profile_form.save()
            requirements_form.save()
            for i in range(len(toolFormSet)):
                # update the skill level
                tool_qs[i].skill_level = toolFormSet[i].fields['skill_level']       
        else:
            print(profile_form.errors, requirements_form.errors)
    else:
        profile_form = ProfileForm(instance=user_profile)
        requirements_form = RequirementsForm(instance=user_profile.requirements)
        toolFormSet = ToolFormSet(initial=tools)
        for form in toolFormSet.forms:
            form.fields['name'].choices = [(form.initial['name'],form.initial['name'])]
    return render(request, 'making/update_profile.html', context={'user_profile': user_profile, 'profile_form':profile_form, 'requirements_form':requirements_form, 'toolFormSet':toolFormSet})

# passes list of profiles to template
@login_required
def select_profile(request):
    user = request.user
    user_profile = getProfile(request)
    profile_choices = UserProfile.choices_objects.get_choices(user.pk)
    # if they dont have any profiles, redirect to create_profile
    if not profile_choices:
        return redirect(reverse('making:create_profile'))
    no_profiles = len(profile_choices)
    
    switch_form = SwitchProfileForm()
    switch_form.fields['profile'].choices = profile_choices

    if request.method == 'POST':
        switch_form = SwitchProfileForm(request.POST)
        # if i dont have line below, it will fail validation (because the form doesn't know the correct choices)
        switch_form.fields['profile'].choices = profile_choices
        if switch_form.is_valid():
            # ID of the chosen profile
            request.session['user_profile'] = switch_form['profile'].value()      
            # re-run this function to get the new user profile object
            user_profile = getProfile(request)     
        else:
            print(switch_form.errors)
    else:
        switch_form = SwitchProfileForm()
        switch_form.fields['profile'].choices = profile_choices

src/making/templates/making/about.html
{% extends 'making/index.html' %}
{% block title %}
About -
{% endblock %}
{% block page_title %}
About -
{% endblock %}
{% block body %}
    about <br>
{% endblock %}

src/making/templates/making/add_tool.html
{% extends 'making/index.html' %}
{% load static %}

{% block title %}
Add Tools -
{% endblock %}
{% block page_title %}
Add Tools
{% endblock %}

{% block body %}
{% if error %}
You cannot add a tool you already have. Update it instead. <br>
{% endif %}
{% if success %}
Tool added successfully. <br>
{% endif %}
<p>
<form method="post" action="{% url 'making:add_tool' %}">
    {% csrf_token %}
    {{ toolFormSet.management_form }}
    <div id="form_set">
        {% for i in toolFormSet %}   
            <div class="no_error">
                {{ i }} 
            </div>
        {% endfor %}   
    </div>
    <input type="button" value="+" id="add_more" class="mt-4 px-2 pt-0" />
    <input type="button" value="-" id="delete" class="mx-3 px-2 pt-0"/> <br>
    <input type="submit" value="Submit" id="submit" class="mt-2"/> 
    <div id="empty_form" style="display:none">
        <div class="no_error">
            <br> {{ toolFormSet.empty_form }}
        </div>
    </div>
</form> 
</p>

<script src="{% static 'making/js/addToolForm.js' %}"></script>
<script>
    document.querySelector('#add_more').addEventListener("click",addForm)   
</script>
<!-- messy way of passing in parameter value -->
<script>
    document.querySelector('#delete').addEventListener("click",function() {
        deleteForm(1);
    })   
</script>

{% endblock %}

src/making/templates/making/create_profile.html
{% extends 'making/index.html' %}
{% load static %}
{% block title %}
Create Profile
{% endblock %}
{% block page_title %}
Create Profile
{% endblock %}


{% block body %}
{% if registered %}
<p class="lead">Profile created. Welcome {{ user_profile.profile_name }}! </p>
{% endif %}
<form method="post" action="{% url 'making:create_profile' %}">
    {% csrf_token %}
    {{ profile_form.as_p }}
    {% for field in requirements_form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        <div><b>{{ field.label_tag }} </b></div>
        <div>{{ field.help_text }}</div>
        <div>{{ field }}</div>
        <br>
    </div>
    {% endfor %}

    <h6><b>Tools</b></h6>
    <ul class="list-unstyled">
        <li>These are what physical tools you have access to. </li> <br>
        <li>Skill level is how much you have used that tool before. </li>
        <li>None: means you have the tool but have not used it before. </li>
        <li>Beginner: means you have used the tool only a few times.</li>
        <li>Competent: means you have used the tool several times. </li>
        <li>Expert: means you have used the tool a lot and are confident using it.</li>
    </ul>

    {{ toolFormSet.management_form }}
    <div id="form_set">
    {% for i in toolFormSet %}
        <div class="no_error">
            {{ i }}
        </div>
    {% endfor %}
    </div>
    <input type="button" value="Add Tool" id="add_more" />
    <input type="button" value="Delete Tool" id="delete" class="mx-4"/> <br>
    <input type="submit" value="Create Profile" id="submit" class="mt-4"/>
    <div id="empty_form" style="display:none">
        <div class="no_error">
            {{ toolFormSet.empty_form }} <br><br>
        </div>
    </div>
</form>

<script src="{% static 'making/js/addToolForm.js' %}"></script>
<script>
    document.querySelector('#add_more').addEventListener("click",addForm)
</script>
<script>
    document.querySelector('#delete').addEventListener("click",deleteForm)
</script>

{% endblock %}

src/making/templates/making/create_syllabus.html
{% extends 'making/index.html' %}
{% load static %}
{% block title %}
Create Syllabus -
{% endblock %}
{% block page_title %}
Create Syllabus
{% endblock %}
{% block body %}
<p> A syllabus is a path of projects to follow to help you gain the skills needed to carry out a more difficult project that you'd like to do. This more difficult project is your "end project". </p>
<p>
<form method="post" action="{% url 'making:create_syllabus' %}">
    {% csrf_token %}
    {{ syllabus_form }}
    <input type="submit" name="submit" value="Submit" />
</form>
</p>
{% if syllabus %}
Syllabus: <br>
{% for i in projects %}
      {{ forloop.counter }}. <a href="{% url 'making:project' i.pk %}">{{ i.title }}:</a>
      {{ i.description }} <br>
      {% if i.thumbnail %}
        <img src="{% static i.thumbnail %}" /> <br>
      {% endif %}
{% endfor %}
{% endif %}


{% endblock %}

src/making/templates/making/index.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}Making Projects</title>  
    <link
    href="{% static "making/css/bootstrap.min.css" %}"
    rel="stylesheet">
    <link
    href="{% static "making/css/additional.css" %}"
    rel="stylesheet">
</head>

<body class="d-flex flex-column min-vh-100">
  <!-- link for screen readers, to let them skip navbar and go straight to content -->
  <div class="skippy visually-hidden-focusable overflow-hidden">
    <a href="#content">Skip to content</a>
  </div>

  <header class="text-bg-primary static-top">
    <div class="container-md">
      <nav id="navbar-nav" class="col-md-8 mx-auto navbar navbar-expand-md navbar-dark bd-navbar">
        <a class="navbar-brand" href="{% url 'making:index' %}">Making Projects</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item" id="projects-link"><a class="nav-link" href="{% url 'making:projects' %}">Projects</a></li>    
            {% if user.is_authenticated %}
              {% if user_profile %}
                <li class="nav-item" id="view-profile-link"><a class="nav-link" href="{% url 'making:view_profile' %}">View Profile</a></li>
                <li class="nav-item" id="select-profile-link"><a class="nav-link" href="{% url 'making:select_profile' %}">Select Profile</a></li>
                <li class="nav-item" id="add-tool-link"><a class="nav-link" href="{% url 'making:add_tool' %}">Add Tool</a></li>
                <li class="nav-item" id="create-syllabus-link"><a class="nav-link" href="{% url 'making:create_syllabus' %}">Create Syllabus</a></li>
              {% else %}
                <li class="nav-item" id="create-profile-link"><a class="nav-link" href="{% url 'making:create_profile' %}">Create Profile</a></li>
              {% endif %}
              <li class="nav-item" id="logout-link"><a class="nav-link" href="{% url 'making:logout' %}">Logout</a></li>
            {% else %}
              <li class="nav-item" id="register-link"><a class="nav-link" href="{% url 'making:register' %}">Register</a></li>         
              <li class="nav-item" id="login-link"><a class="nav-link" href="{% url 'making:login' %}">Login</a></li>    
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
  </header>

  <div id="content" class="container-md pt-2">
    <div class="col-md-8 mx-auto">
      <h1>
      {% block page_title %}      
      {% endblock %}
      </h1>
      {% block body %}
      <p> Welcome to Making Projects! </p>
      <p> Here you can view project tutorials in a way that is accessible to <b>you</b>. <br>
        There is a library of projects here that are adapted to fit your needs. <br>
        You can view all the projects without creating an account, but you need one to have a project customised for you. <br>
        As well as individual projects, you can make a "syllabus" which will give you a path of projects to follow to help you gain the skills needed to carry out a more complex project that you'd like to do. </p>
        <a href="{% url 'making:projects' %}">Explore the projects</a> <br>
      <a href="{% url 'making:register' %}">Create an account</a>
      {% endblock %}
    </div>
  </div>

<footer class="footer py-4 text-bg-white mt-auto">
    
</footer>

<script src="{% static "making/js/bootstrap.min.js" %}"></script>
</body>
</html>

src/making/templates/making/login.html
{% extends 'making/index.html' %}
{% block title %}
Login -
{% endblock %}
{% block page_title %}
Login
{% endblock %}
{% block body %}
{% if error %}
Login details incorrect. <br>
{% endif %}

<form method="post" action="{% url 'making:login' %}">
    {% csrf_token %}
    {{ user_form }}
    <input type="submit" name="submit" value="Login" /> 
</form>

{% endblock %}

src/making/templates/making/project.html
{% extends 'making/index.html' %}
{% load static %}
{% block title %} {{ project.title }} - {% endblock %}

{% block page_title %}
{{ project.title }}
{% endblock %}

{% block body %}
{% if project %}
    <p>{{ project.description }} </p>
        <!-- this is image stuff -->
    {% for i in paths %}
       <img src="{% static i %}" class="img-fluid"/>
    {% endfor %}
    <p><b>Materials:</b> <br>
    {% for i in project.materials %}
        - {{ i }} <br>
    {% endfor %}</p>


    {% if user_profile %}
    <p><table class="table">
        <tr>
          <th></th>
          <th>Project</th>
          <th>Your Profile</th>
        </tr>
        <tr>
          <th>Vision</td>
          <td>{{ project.vision }}</td>
          <td>{{ user_profile.vision }}</td>
        </tr>
        <tr>
            <th>Dexterity</th>
            <td>{{ project.dexterity }}</td>
            <td>{{ user_profile.dexterity }}</td>
        </tr>
        <tr>
            <th>Language</th>
            <td>{{ project.language }}</td>
            <td>{{ user_profile.language }}</td>
        </tr>
        <tr>
            <th>Memory</th>
            <td>{{ project.memory }}</td>
            <td>{{ user_profile.memory }}</td>
        </tr>
      </table>
     </p>
    {% else %}
    <p><b>Project information:</b> <br>
    Vision: {{ project.vision }} <br>
    Dexterity: {{ project.dexterity }} <br>
    Language: {{ project.language }} <br>
    Memory: {{ project.memory }} <br> </p>
    {% endif %}

    {% if project.tools %}
    <p><b>Tools:</b> <br>
    {% for i in project.tools %}
        {{ i.name }}: {{i.skill_level }} <br>
    {% endfor %}
    </p>
    {% endif %}


    <p><b>Instructions: </b> <br>
    {% for i in project.instructions %}
        {{ forloop.counter }}. {{ i }} <br>
    {% endfor %} </p>


{% endif %}
{% endblock %}

src/making/templates/making/projects.html
{% extends 'making/index.html' %}
{% load static %}
{% block title %} Projects - {% endblock %}
{% block page_title %}
Projects
{% endblock %}
{% block body %}

{% for i in projects %}  
      <a href="{% url 'making:project' i.pk %}">{{ i.title }}:</a>
      {{ i.description }} <br>
      {% if i.thumbnail %}
        <img src="{% static i.thumbnail %}" /> <br>
      {% endif %}
{% endfor %}


{% endblock %}

src/making/templates/making/register.html
{% extends 'making/index.html' %}
{% block title %}
Register -
{% endblock %}
{% block page_title %}
Register
{% endblock %}
{% block body %}

<form method="post" action="{% url 'making:register' %}">
    {% csrf_token %}
    {{ user_form }}
    <input type="submit" name="submit" value="Register" /> 
</form>

{% if error %} 
    There has been an error in registering. 
{% endif %}

{% endblock %}

src/making/templates/making/select_profile.html
{% extends 'making/index.html' %}
{% block title %}
    {% if user_profile %}
        Switch Profile -
    {% else %}
        Select Profile -
    {% endif %}
{% endblock %}

{% block page_title %}
    {% if user_profile %}
        Switch Profile
    {% else %}
        Select Profile
    {% endif %}
{% endblock %}

{% block body %}

<!-- The user does not have any profiles -->
{% if not no_profiles  %}
    <p>You don't currently have any profiles. <br>
    <a href="{% url 'making:create_profile' %}">Create one here.</a></p>
<!-- The user only has 1 profile -->
{% elif no_profiles == 1 %}
    <p>You currently only have one profile. <br>
    <a href="{% url 'making:create_profile' %}">Create another one here.</a></p>
{% else %} 
    <!-- The user has already selected a profile this session -->
   <p>
    {% if user_profile %}
        Switch your current user profile! <br>
        Your current profile is: {{ user_profile.profile_name }}
    <!-- the user has not selected a profile for this session -->
    {% else %}
        Please select a user profile <br>
    {% endif %}
   </p> 
    <form method="post" action="{% url 'making:select_profile' %}">
        {% csrf_token %}
        {{ switch_form }}
        <input type="submit" name="submit" value="Submit" /> 
    </form>
{% endif %}

{% endblock %}

src/making/templates/making/update_profile.html
{% extends 'making/index.html' %}
{% load static %}
{% block title %}
Update Profile -
{% endblock %}
{% block page_title %}
Update Profile
{% endblock %}

{% block body %}

<form method="post" action="{% url 'making:update_profile' %}">
    {% csrf_token %}
    {{ profile_form.as_p }}
    {% for field in requirements_form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        <div><b>{{ field.label_tag }} </b></div> 
        <div>{{ field.help_text }}</div>
        <div>{{ field }}</div>
        <br>
    </div>
    {% endfor %}

    <h6><b>Tools</b></h6>

    <ul class="list-unstyled">
        <li>These are what tools you have access to. </li>
        <li>Skill level is how much experience you have with that tool. </li>
        <li>None: means you have the tool but have not used it before. </li>
        <li>Low: means you have used the tool a few times.</li>
        <li>Medium: means you have used the tool ??? </li>
        <li>High: means you have used the tool a lot.</li>
    </ul>
    
    {% for tool_form in toolFormSet %}
    {{ tool_form }}   <br>
    {% endfor %}

<input type="submit" value="Update Profile" id="submit" class="mt-4"/> 

</form>

{% endblock %}

src/making/templates/making/view_profile.html
{% extends 'making/index.html' %}
{% block page_title %}
View Profile
{% endblock %}

{% block body %}
<p>
User's email: {{ user.username }}<br>
Profile's name: {{ profile.profile_name }}<br>
Vision: {{ profile.vision }} <br>
Dexterity: {{ profile.dexterity }} <br>
Language: {{ profile.language }} <br>
Memory: {{ profile.memory }} <br> </p>

{% if profile.tools %}
<p>
<b>Tools:</b> <br>
    {% for tool in profile.tools %}
        {{ tool.name }}: {{ tool.skill_level }} <br>
    {% endfor %}
</p>
{% endif %}
<a href="{% url 'making:update_profile' %}">Update profile.</a> <a href="{% url 'making:create_profile' %}">Create new profile.</a>


{% endblock %}